services:
    node:
        container_name: pre_reactapp
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
            args:
                - UID=${UID}
                - GID=${GID}
                - USERNAME=${USERNAME}
        tty: true
        user: ${UID}:${GID}
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
        volumes:
            - ./:/app
        ports:
            - 5173:5173
